# Generated by Django 6.0.4 on 2026-04-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=250)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('business_analysis', 'Business Analysis'), ('project_management', 'Project Management'), ('digital_transformation', 'Digital Transformation'), ('process_improvement', 'Process Improvement'), ('data_analytics', 'Data & Analytics'), ('crm_erp', 'CRM / ERP Implementation'), ('other', 'Other')], default='other', max_length=50)),
                ('short_description', models.CharField(help_text='One-line summary shown on the card', max_length=300)),
                ('description', models.TextField(help_text='Full project description')),
                ('tools_used', models.CharField(help_text='Comma-separated list, e.g. "Jira, Confluence, SQL"', max_length=300)),
                ('outcome', models.TextField(blank=True, help_text='Key results or impact achieved')),
                ('client_or_company', models.CharField(blank=True, help_text='Client or employer (optional)', max_length=150)),
                ('duration', models.CharField(blank=True, help_text='e.g. "6 months" or "Jan 2023 – Jul 2023"', max_length=100)),
                ('featured', models.BooleanField(default=False, help_text='Show on homepage highlights')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order — lower numbers appear first')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
