# Generated by Django 6.0.4 on 2026-04-25 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_project_github_url_project_live_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_file',
            field=models.FileField(blank=True, help_text='Downloadable project file (ZIP, PDF, etc.)', null=True, upload_to='project_files/'),
        ),
    ]
