# Generated by Django 6.0.4 on 2026-04-28 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_add_project_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='video',
            field=models.FileField(blank=True, help_text='Project demo video (MP4)', null=True, upload_to='project_videos/'),
        ),
    ]
