# Generated by Django 6.0.4 on 2026-05-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_add_project_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='business_problem',
            field=models.TextField(blank=True, help_text='The business problem or challenge this project addressed'),
        ),
        migrations.AddField(
            model_name='project',
            name='key_features',
            field=models.TextField(blank=True, help_text='Key features or deliverables (one per line)'),
        ),
        migrations.AddField(
            model_name='project',
            name='role_contribution',
            field=models.TextField(blank=True, help_text='Your specific role and contributions on this project'),
        ),
    ]
