# Generated by Django 6.0.4 on 2026-05-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_add_project_detail_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='gallery_images',
            field=models.CharField(blank=True, help_text='Comma-separated image filenames for the gallery, e.g. "chart1.png, chart2.png"', max_length=1000),
        ),
    ]
