# Generated by Django 6.0.4 on 2026-05-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_add_gallery_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='biggest_challenge',
            field=models.TextField(blank=True, help_text='The biggest challenge faced during this project'),
        ),
        migrations.AddField(
            model_name='project',
            name='what_you_learned',
            field=models.TextField(blank=True, help_text='Key takeaways or lessons learned'),
        ),
    ]
